### ISSUE TITLE
Hugo error with multiple `menu: false` pages

### ISSUE THREAD

**Issue by geealbers** [gettypubs/quire#105]
We provide a number of display flags to control what pages show up in which outputs and in which parts of the site navigation. They include:

```yaml
pdf: false
online: false
epub: false
toc: false
menu: false
```

For the first time, I'm trying a book with multiple pages that I don't want displayed in the Menu, and it resulted in the following error and a build/preview failure:

```
ERROR 2018/12/20 15:37:25 Two or more menu items have the same name/identifier in Menu "false": "". 
Rename or set an unique identifier.
```

It's unfortunately not consistent. Sometimes I've been able to do test projects where I don't get that error and the `menu: false` works as expected. Nonetheless I think the issue must be stemming from [Hugo's own use of `menu`](https://gohugo.io/content-management/menus/#readout). 

One solution would be to rename `menu` to something else. However all our documentation and template language use "menu" do describe what that nav is. Instead I'd propose we put all these flags under a single `display` group. This means making changes to all the variant controls (pdf, online, epub, etc.) but in the longterm will serve us better, and makes for a cleaner model.

```yaml
display:
  pdf: false
  online: false
  epub: false
  toc: false
  menu: false
```
