### ISSUE TITLE
New Theme: Style variables

### ISSUE THREAD

**Issue by geealbers** [gettypubs/quire#109]
For the style variables, and for colors especially, I want to make sure we can quickly change a value in a single location and have it change everywhere it's supposed to in the layouts. Currently that's not the case. I'm also hoping to simplify and rationalize some things to limit the number of variables we need to spec (again, especially colors). Linked below is a PDF of some ugly functional samples trying to demonstrate how I think the color variables should play out. In the upper left corner of each image I stuck a little sticky note comment with what the variables were. Hope it's useful.

--> [quire-color-examples.pdf](https://github.com/gettypubs/quire/files/2767319/quire-color-examples.pdf)

Otherwise, here are the changes I think should be made. Let me know if you have questions or if you want to sit down and talk this out together.

- [ ] Rename `$theme` and `$navbar` variable values. Instead of primary or secondary, it should be modern or classic; and instead of normal or inverse, it should be normal or accent.

- [ ] Establish and use three color variables to be exposed at the top level of the file and which will control ALL theme colors globally:

    ```scss
    $accent-color
    $content-background-color
    $secondary-background-color
    ```

    All other variants needed in the design should be derived as % lighting or darkening of these three colors. The exceptions are the highlight color, which is it's own thing but doesn't need to be exposed at the top level, and the font colors, which should be automatically generated (see next item).

    So, the top of variables file would look something like the following. I'd ideally like not to expose the `@if $theme ==` logic here, but I couldn't think of an elegant way to do so.

    ```scss
    // Theme variant: modern or classic
    $theme: modern;

    // Navbar style: normal or accent
    $navbar: normal;

    // Colors 
    @if $theme == modern {
      $accent-color: #cf4747;
      $content-background-color: #fff;
      $secondary-background-color: #eef2f3;
    }

    @if $theme == classic {
      $accent-color: #6a8eb8;
      $content-background-color: #fff;
    }
    ```

    Once we get Hugo pipes working, these would be the variables we'd want to expose there. Along, perhaps, with the option to choose serif or sans-serif for the header, body, and small text fonts. (But that's for another day.)

- [ ] Add logic to automatically color all the type depending on the lightness of the `$content-background-color`. (There are probably a number of ways to do this, but this is an example I've referenced before myself --> http://thesassway.com/intermediate/dynamically-change-text-color-based-on-its-background-with-sass.) If the background color is light, the type should be dark, whereas if the background color is dark, the type should be light. There are a lot of variants (9!) in the grays used currently. I'd like to recommend flattening them to just 4 values, which could be used in pairs for the type whether it's regular or inverse. @rtapales maybe wants to weigh in on the specific values, but I was thinking something like:

    ```scss
    // Regular type
    $font-color-main: #333;
    $font-color-secondary: #666;

    // Inverse type
    $font-color-main: #fff;
    $font-color-secondary: #999;
    ```

- [ ] Add logic to determine color of progress bar background. The progress bar background is a version of the content background color. If the background color is light, the progress bar is a darker version of that color. If the background color is dark, the progress bar is a lighter version.
