### ISSUE TITLE
Add object.yml and Object content model

### ISSUE THREAD

**Issue by geealbers** [gettypubs/quire#21]
For collection catalogues, Quire publications need to be able to handle Objects. Currently adding an `object` item with a number of arbitrary sub-attributes to the page YAML of a `type: entry` page will generate a table in the layout displaying that information.

```yaml
title: The Luncheon on the Grass
weight: 101
object:
  artist: Édouard Manet
  year: 1863
  medium: Oil on canvas
  dimensions: 208 cm × 264.5 cm (81.9 in × 104.1 in)
  location: Musée d’Orsay, Paris
image: manet.jpg
type: entry
```

<img width="1137" alt="screen shot 2018-01-29 at 3 48 59 pm" src="https://user-images.githubusercontent.com/7796401/35540710-1417ed96-050c-11e8-984a-ca455dd77d5c.png">

Along with this behavior, users should also be able to reference objects listed in an `objects.yml` file in the `data` directory by an `id`, rather than having the object data embedded directly in the page. 

As mentioned above, the items listed under `object` are currently totally arbitrary. Whatever is listed there is automatically included in the generated table and there's nothing to say that the attributes will be consistent from project to project, or even from page to page. However, in its content model, Quire must define some attributes as specific, such as `id` so that we can meaningfully make use of them in templates. The obvious candidates might be those that are more regularized and data driven, such as `start_date` and `end_date`, or `height` and `width`. These in particular would let us implement sorting by dates, or showing a diagram of relative dimensions, both of which have been popular features in past catalogues. Are there other attributes like these that we should define as specific to an Object in Quire?

- Can/should Objects have Figures?
- Do we integrate Getty vocabs in some way to allow for more cross-linking? Meaning, can an Object have a Subject?
- In the case above, the `object` doesn't actually have a `title` of its own, the Page does. This is odd, but is it avoidable if every page has to have a `title`? Otherwise we're duplicating the `title` in two different places, which goes against our best practices.
