### ISSUE TITLE
Error: Error building site: logged 3 error(s)

### ISSUE THREAD

**Issue by MartianBear** [gettypubs/quire#85]
I'm getting this error when I run "quire preview". Worked earlier in the day, then I made a bunch of changes to the copy and last night when I tried messing with it some more, I started getting errors and could not restart it to show at http://localhost:1313

**Comment by naeluh** [comment]
Hi @MartianBear what error did you get? 
thanks!

**Comment by MartianBear** [comment]
When I try running "quire preview" I get the error message, no info, and then "Shutting Quire down". When I run "quire pdf", I get the following: 

(node:2286) UnhandledPromiseRejectionWarning: Error: Error building site: logged 3 error(s)

(node:2286) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:2286) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
prince: warning: disabled parallel downloads: failed to initialise locking for OpenSSL
prince: http://localhost:1313/: error: Failed to connect to localhost port 1313: Connection refused
prince: http://localhost:1313/: error: could not load input file
prince: error: failed to load all input documents
PDF output to: static/downloads/output.pdf
jhope-mpl13:french-paintings jhope$ quire preview
Launching preview server
Navigate to http://localhost:1313 to see your changes.
Press Control+C or type "quire stop" to stop the preview.
Error: Error building site: logged 3 error(s)

I'm still very new with Quire and Git, so I'm not the hottest hand when it comes to playing with the terminal.

**Comment by naeluh** [comment]
can you try running 

`quire preview -v`

also can you run 

`quire install `

inside your quire directory

and then try 

`quire preview -v `

again

**Comment by MartianBear** [comment]
object_display_order:
  - artist
  - year
  - dimensions
  - medium
  - location
object_list:
  - id: 1
    title: *The Title*
    artist: A painter
    year: 1863
    medium: Oil on canvas
    dimensions: 208 cm × 264.5 cm (81.9 in × 104.1 in)
    location: The Nelson-Atkins Museum of Arts
    link:
    figure:
      - id: "1.1"
  - id: 2
    title: Impression, *Sunrise*
    artist: Claude Monet
    year: 1872
    medium: Oil on canvas
    dimensions: 48 cm × 63 cm (18.9 in × 24.8 in)
    location: Musée Marmottan Monet, Paris
    link:
    figure:
      - id: "1.2"
  - id: 3
    title: Reading (portrait of Edma Morisot)
    artist: Berthe Morisot
    year: 1873
    medium: Oil on fabric
    dimensions: 74.2 x 100.3 x 12 cm (29 <sup>3</sup>⁄<sub>16</sub> x 39 <sup>1</sup>⁄<sub>2</sub> x 4 <sup>11</sup>⁄<sub>16</sub> in.)
    location: Cleveland Museum of Art
    link: http://www.clevelandart.org/art/1950.89
    download: true
    figure:
      - id: "1.3"
      - id: "1.4"
      - id: "1.5"

**Comment by naeluh** [comment]
Is that exactly what the code file looks like ? 
What editor are you using ?

Can you try this instead ?

```
object_display_order:
  - artist
  - year
  - dimensions
  - medium
  - location
object_list:
  -
    id: 1
    title: 'The Title'
    artist: 'A painter'
    year: 1863
    medium: 'Oil on canvas'
    dimensions: '208 cm × 264.5 cm (81.9 in × 104.1 in)'
    location: 'The Nelson-Atkins Museum of Arts'
    link: null
    figure:
      -
        id: '1.1'
  -
    id: 2
    title: 'Impression, Sunrise'
    artist: 'Claude Monet'
    year: 1872
    medium: 'Oil on canvas'
    dimensions: '48 cm × 63 cm (18.9 in × 24.8 in)'
    location: 'Musée Marmottan Monet, Paris'
    link: null
    figure:
      -
        id: '1.2'
  -
    id: 3
    title: 'Reading (portrait of Edma Morisot)'
    artist: 'Berthe Morisot'
    year: 1873
    medium: 'Oil on fabric'
    dimensions: '74.2 x 100.3 x 12 cm (29 3⁄16 x 39 1⁄2 x 4 11⁄16 in.)'
    location: 'Cleveland Museum of Art'
    link: 'http://www.clevelandart.org/art/1950.89'
    download: true
    figure:
      -
        id: '1.3'
      -
        id: '1.4'
      -
        id: '1.5'
```
